// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TeamsTranscript.Specs
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("TranscriptionExtensions")]
    public partial class TranscriptionExtensionsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "TranscriptionExtensions.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "TranscriptionExtensions", "I want to be able to easily process or transform collections of Transcription dat" +
                    "a structures\r\nSo that I can better perform information extraction processes.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generate a distinct list of participants from a Transcription")]
        [NUnit.Framework.CategoryAttribute("tag1")]
        public void GenerateADistinctListOfParticipantsFromATranscription()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generate a distinct list of participants from a Transcription", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "start",
                            "end",
                            "speaker",
                            "script"});
                table2.AddRow(new string[] {
                            "0:0:0.0",
                            "0:0:1.250",
                            "Joe MacMillan",
                            "Hi I\'m Jane Doe, CEO."});
                table2.AddRow(new string[] {
                            "0:0:2.90",
                            "0:0:4.480",
                            "Gordon Clark",
                            "Hi, I\'m John Doe, no relation, Ha! COO."});
                table2.AddRow(new string[] {
                            "0:0:3.520",
                            "0:0:5.460",
                            "Cameron Howe",
                            "Today I want to discuss the plans for the next financial year."});
                table2.AddRow(new string[] {
                            "0:0:5.300",
                            "0:0:5.910",
                            "Donna Clark",
                            "This year has been turbulent, next year is predicted to be too."});
                table2.AddRow(new string[] {
                            "0:0:7.80",
                            "0:0:8.180",
                            "John Bosworth",
                            "And the turbulence hasn\'t been restricted to a single region."});
                table2.AddRow(new string[] {
                            "0:0:8.810",
                            "0:0:9.500",
                            "Cameron Howe",
                            "It\'s been a global trend"});
                table2.AddRow(new string[] {
                            "0:0:10.690",
                            "0:0:11.510",
                            "Joe MacMillan",
                            "And that\'s what\'s worrisome, and why we need a plan."});
#line 8
 testRunner.Given("I have the following transcription entries:", ((string)(null)), table2, "Given ");
#line hidden
#line 17
 testRunner.When("I ask for a distinct list of participants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "name"});
                table3.AddRow(new string[] {
                            "Cameron Howe"});
                table3.AddRow(new string[] {
                            "Donna Clark"});
                table3.AddRow(new string[] {
                            "Gordon Clark"});
                table3.AddRow(new string[] {
                            "Joe MacMillan"});
                table3.AddRow(new string[] {
                            "John Bosworth"});
#line 18
 testRunner.Then("I should get a list of participants with the following content:", ((string)(null)), table3, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generate a comma separated list of participants from a Transcription")]
        public void GenerateACommaSeparatedListOfParticipantsFromATranscription()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generate a comma separated list of participants from a Transcription", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "start",
                            "end",
                            "speaker",
                            "script"});
                table4.AddRow(new string[] {
                            "0:0:0.0",
                            "0:0:1.250",
                            "Joe MacMillan",
                            "Hi I\'m Jane Doe, CEO."});
                table4.AddRow(new string[] {
                            "0:0:2.90",
                            "0:0:4.480",
                            "Gordon Clark",
                            "Hi, I\'m John Doe, no relation, Ha! COO."});
                table4.AddRow(new string[] {
                            "0:0:3.520",
                            "0:0:5.460",
                            "Cameron Howe",
                            "Today I want to discuss the plans for the next financial year."});
                table4.AddRow(new string[] {
                            "0:0:5.300",
                            "0:0:5.910",
                            "Donna Clark",
                            "This year has been turbulent, next year is predicted to be too."});
                table4.AddRow(new string[] {
                            "0:0:7.80",
                            "0:0:8.180",
                            "John Bosworth",
                            "And the turbulence hasn\'t been restricted to a single region."});
                table4.AddRow(new string[] {
                            "0:0:8.810",
                            "0:0:9.500",
                            "Cameron Howe",
                            "It\'s been a global trend"});
                table4.AddRow(new string[] {
                            "0:0:10.690",
                            "0:0:11.510",
                            "Joe MacMillan",
                            "And that\'s what\'s worrisome, and why we need a plan."});
#line 27
 testRunner.Given("I have the following transcription entries:", ((string)(null)), table4, "Given ");
#line hidden
#line 36
 testRunner.When("I ask for a comma separated list of participants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "list"});
                table5.AddRow(new string[] {
                            "Cameron Howe, Donna Clark, Gordon Clark, Joe MacMillan, John Bosworth"});
#line 37
 testRunner.Then("I should get a comma separated list of participants with the following content:", ((string)(null)), table5, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Filter Transcription by timespan range")]
        public void FilterTranscriptionByTimespanRange()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Filter Transcription by timespan range", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "start",
                            "end",
                            "speaker",
                            "script"});
                table6.AddRow(new string[] {
                            "0:1:0.0",
                            "0:1:1.250",
                            "Joe MacMillan",
                            "Hi I\'m Jane Doe, CEO."});
                table6.AddRow(new string[] {
                            "0:2:2.90",
                            "0:2:4.480",
                            "Gordon Clark",
                            "Hi, I\'m John Doe, no relation, Ha! COO."});
                table6.AddRow(new string[] {
                            "0:3:3.520",
                            "0:3:5.460",
                            "Cameron Howe",
                            "Today I want to discuss the plans for the next financial year."});
                table6.AddRow(new string[] {
                            "0:4:5.300",
                            "0:4:5.910",
                            "Donna Clark",
                            "This year has been turbulent, next year is predicted to be too."});
                table6.AddRow(new string[] {
                            "0:5:7.80",
                            "0:5:8.180",
                            "John Bosworth",
                            "And the turbulence hasn\'t been restricted to a single region."});
                table6.AddRow(new string[] {
                            "0:6:8.810",
                            "0:6:9.500",
                            "Cameron Howe",
                            "It\'s been a global trend"});
                table6.AddRow(new string[] {
                            "0:7:10.690",
                            "0:7:11.510",
                            "Joe MacMillan",
                            "And that\'s what\'s worrisome, and why we need a plan."});
#line 42
 testRunner.Given("I have the following transcription entries:", ((string)(null)), table6, "Given ");
#line hidden
#line 51
testRunner.When("I ask for transcriptions between 0:3:0.0 and 0:6:0.0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "start",
                            "end",
                            "speaker",
                            "script"});
                table7.AddRow(new string[] {
                            "0:3:3.520",
                            "0:3:5.460",
                            "Cameron Howe",
                            "Today I want to discuss the plans for the next financial year."});
                table7.AddRow(new string[] {
                            "0:4:5.300",
                            "0:4:5.910",
                            "Donna Clark",
                            "This year has been turbulent, next year is predicted to be too."});
                table7.AddRow(new string[] {
                            "0:5:7.80",
                            "0:5:8.180",
                            "John Bosworth",
                            "And the turbulence hasn\'t been restricted to a single region."});
#line 52
 testRunner.Then("I should get the following transcriptions:", ((string)(null)), table7, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
